CREATE TABLE "MISDEV"."SPS_COST_CALCULATION_MASTER"
(
    DEPT_ID char(6) NOT NULL,
    ESTIMATE_TYPE varchar2(4) NOT NULL,
    COMBINATION_ENTRIES varchar2(200),
    PRIORITY char(2),
    ENTRY_CD varchar(20),
    ENTRY_TYPE varchar(20),
    PERCENTAGE number(5,2),
    EFFECTIVE_FROM date NOT NULL,
    EFFECTIVE_TO date NOT NULL,
    CONSTRAINT PK_COST_CALCULATION PRIMARY KEY (DEPT_ID,ESTIMATE_TYPE,ENTRY_CD)
)
;
 ALTER TABLE SPS_COST_CALCULATION_MASTER ADD  (fundid varchar2(6))
 alter table SPS_COST_CALCULATION_MASTER modify PERCENTAGE number(5,2);

CREATE TABLE "MISDEV"."SPS_ESTIMATETYPES"
(
   DEPT_ID char(6) NOT NULL,
   ESTIMATE_TYPE varchar2(4) NOT NULL,
   BRANCH_CODE varchar2(200),
   BRANCH char(2),
   DESCRIPTION varchar2(20) NOT NULL,
   EFFECTIVE_FROM date NOT NULL,
   EFFECTIVE_TO date NOT NULL,
   CONSTRAINT PK_SPS_ESTIMATETYPES PRIMARY KEY (DEPT_ID,ESTIMATE_TYPE)
)
;
-----------run on SMC tables-----------
alter table APPROVAL modify STANDARD_COST number(20,2);
alter table APPROVAL modify DETAILED_COST number(20,2);


--alter table APPESTLIM modify APPLICATION_TYPE varchar(3);

alter table PIV_DETAIL modify CONFIRMED_BY varchar(20);

alter table estimate_referencebs add FILE_REF varchar2(100);

drop index UC_SPESTEDY_CONS

ALTER TABLE SPESTEDY_CONS
drop column TIME_SESSION

ALTER TABLE SPESTEDY_CONS add  westimate_no varchar2(20)

ALTER TABLE SPESTEDY_CONS modify  westimate_no default 0

 ALTER TABLE SPESTEDY_CONS
  MODIFY WESTIMATE_NO DEFAULT 0
  

  
  -----------------------------------------
  
  CREATE TABLE "MISDEV"."SPESTEDY_CONS"
(
   APPOINTMENT_ID varchar2(11) NOT NULL,
   DEPT_ID char(6) NOT NULL,
   APPOINMENT_TYPE varchar2(10),
   REFERENCE_NO varchar2(20),
   APPOINTMENT_DATE date,
   SUBURB varchar2(50),
   STATUS char(1),
   ALLOCATED_BY varchar2(10),
   ALLOCATED_DATE date,
   ALLOCATED_TIME varchar2(11),
   ALLOCATED_TO varchar2(10),
   DESCRIPTION varchar2(100),
   WESTIMATE_NO varchar2(20),
   TIME_SESSION varchar2(10),
   CONSTRAINT PK_SPESTEDY_CONS PRIMARY KEY (DEPT_ID,APPOINTMENT_ID)
)
;
ALTER TABLE SPESTEDY_CONS
ADD CONSTRAINT FK_SPESTEDY_CONS
FOREIGN KEY (DEPT_ID)
REFERENCES GLDEPTM(DEPT_ID)

  ALTER TABLE SPESTEDY_CONS
  ADD CONSTRAINT UC1_SPESTEDY_CONS UNIQUE (REFERENCE_NO,WESTIMATE_NO,ALLOCATED_TO,Status);
  
  CREATE TABLE "MISDEV"."SPNORMSGROUP"
(
   SECTIONTYPEID varchar2(150) PRIMARY KEY NOT NULL,
   LINEPARENTID varchar2(150),
   DESCRIPTION varchar2(200)
)
;

ALTER TABLE SPNORMS add  LINEPARENTID varchar2(20)

select * from pcesthtt where status=22 and rev_no=2 and dept_id in (543.10,543.20,543.40)

update pcesthtt set status=22 where status=33 and rev_no=2 and dept_id in (543.10,543.20,543.40)

//////////////////////
ALTER TABLE SPNORMSGROUP add  LINESUMMARYID varchar2(40)

---------------------didn' run on PRODMIS and R1,r2.R3.r4-----------
CREATE TABLE "MISDEV"."ALLOCATION_SUMMARY"
(
   AllocationSummary_ID varchar2(30) NOT NULL,
   DEPT_ID char(6) NOT NULL,
   estimateNo varchar2(20),
   lineId varchar2(10),
   lineSummaryId varchar2(25),
   estimatedate date,
   detailCost number(20,2),
   standardCost number(20,2),
   ALLOCATED_TO varchar2(20),
   DESCRIPTION varchar2(400),
   serviceDeponame varchar2(20),
    totalLineLength number(5,2),
   allocatedLineLength number(5,2),
 allocatedEstimatedCost number(20,2),
   totalEstimatedCost number(20,2),
   fundSource varchar2(10),
   CONSTRAINT PK_ALLOCATION_SUMMARY PRIMARY KEY (AllocationSummary_ID,DEPT_ID,estimateNo,lineId)
)
;
ALTER TABLE ALLOCATION_SUMMARY
ADD CONSTRAINT FK_ALLOCATION_SUMMARY
FOREIGN KEY (DEPT_ID)
REFERENCES GLDEPTM(DEPT_ID)

ALTER TABLE ALLOCATION_SUMMARY add  constructionReference varchar2(30)

------------------------------------------

ALTER TABLE SPSTDESTHMT add  ASSIGNEDTO varchar2(30)
------------------added 01/05/2013------------------
 ALTER TABLE WIRING_LAND_DETAIL_CON ADD  (ACCOUNT_NOS varchar2(100))

INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D1','MATERIAL','o','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D2','FP','c','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D3','WAYLEAVES','o','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D4','TRANSPORT','o','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D5','LABOUR','o','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D6','SUBSISTANCES','o','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D7','OVERHEAD','o','2','1');
INSERT INTO "TSTMIS"."SPPEGINFOMATION" (ID,NAME,DESCRIPTION,DEPT_ID,PARENT_ID) VALUES ('D8','OTHER COST','o','2','1');

/////SELECT p.project_No,a.application_id,a.dept_id,p.status FROM Pcesthmt p,Applications a WHERE trim(p.estimate_No)= trim(a.application_No) AND a.application_Sub_Type='FF'



INSERT INTO "MISDEV"."APPESTLIM" (DEPT_ID,APPLICATION_TYPE,USER_LEVEL,LIMIT_FROM,LIMIT_TO,STATUS_FROM,STATUS_TO,UPD_USER,UPD_DATE,UPD_TIME,APPROVAL_TYPE) VALUES ('510.20','DES','DGM',1000000,0,48,23,'IMPORT',{d '2013-01-22'},'11:53:50am','DES');
INSERT INTO "MISDEV"."APPESTLIM" (DEPT_ID,APPLICATION_TYPE,USER_LEVEL,LIMIT_FROM,LIMIT_TO,STATUS_FROM,STATUS_TO,UPD_USER,UPD_DATE,UPD_TIME,APPROVAL_TYPE) VALUES ('510.20','DES','CE',250000,1000000,47,48,'IMPORT',{d '2013-01-22'},'11:53:50am','DES');
INSERT INTO "MISDEV"."APPESTLIM" (DEPT_ID,APPLICATION_TYPE,USER_LEVEL,LIMIT_FROM,LIMIT_TO,STATUS_FROM,STATUS_TO,UPD_USER,UPD_DATE,UPD_TIME,APPROVAL_TYPE) VALUES ('510.20','DES','EE',0,250000,46,47,'IMPORT',{d '2013-01-22'},'11:53:50am','DES');